"""add daily_bars table

Revision ID: 9cb777590c3c
Revises: e25519f24d45
Create Date: 2026-09-04 15:11:01.879239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb777590c3c'
down_revision: Union[str, Sequence[str], None] = 'e25519f24d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_bars',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_paise', sa.BigInteger(), nullable=False),
    sa.Column('high_paise', sa.BigInteger(), nullable=False),
    sa.Column('low_paise', sa.BigInteger(), nullable=False),
    sa.Column('close_paise', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('symbol_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_bars')
    # ### end Alembic commands ###

